[platformio]
src_dir = Core/Src

[env:stm32wle5cc]
platform = ststm32
board = stm32wle5cc

upload_protocol = custom
upload_port = COM19
upload_speed = 115200
upload_command = STM32_Programmer_CLI -c port=$UPLOAD_PORT br=$UPLOAD_SPEED -w $SOURCE 0x08000000 -rst

build_flags =
    -ICore/Inc
    -IDrivers/STM32WLxx_HAL_Driver/Inc
    -IDrivers/STM32WLxx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32WLxx/Include
    -IDrivers/CMSIS/Include
    -DUSE_HAL_DRIVER
    -DSTM32WLE5xx
    -mthumb
    -mcpu=cortex-m4
    -mfloat-abi=soft

build_src_filter =
    +<*>
    +<../Drivers/STM32WLxx_HAL_Driver/Src/*>
    +<../Drivers/CMSIS/Device/ST/STM32WLxx/Source/Templates/gcc/>

board_build.ldscript = STM32WLE5XX_FLASH.ld